# =========================
# WINDOW RULES
# =========================
windowrule=focused_opacity:0.8,unfocused_opacity:0.8,appid:thunar

windowrule=isfloating:1,width:800,height:500,appid:^(com.gabm.satty)$

windowrule=focused_opacity:0.8,unfocused_opacity:0.8,title:^(Wall-Picker)$

windowrule=isfloating:1,width:800,height:500,appid:org.pulseaudio.pavucontrol

windowrule=isfloating:1,width:800,height:500,appid:blueman-manager

#layerrule=noblur:0,layer_name:rofi

windowrule=isfloating:1,width:1000,height:700,appid:^(vlc)$,focused_opacity:1,unfocused_opacity:1

#windowrule=isfloating:1,width:1000,height:700,appid:^(kitty)$

windowrule=isfloating:1,width:1000,height:700,appid:^(mpv)$,focused_opacity:1,unfocused_opacity:1

windowrule=isfloating:1,width:1000,height:700,appid:^(org.kde.gwenview)$,focused_opacity:1,unfocused_opacity:1

windowrule=title:Floating-Menu,isfloating:1,height:0.4,width:0.4
